sudo: required
language: generic
services:
    - docker

before_install: #before our tests get ran
    - docker build -t twohyjr/docker-react -f Dockerfile.dev .

script: #contains all the commands to run our test suite
    - docker run -e CI=true twohyjr/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: docker-react
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-926110576269"
    bucker_path: "docker-react" #the app name
    on:
        branch: master #when we push to master DEPLOY!
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
