version: "3"
services: 
    web:
        build: 
            context: . #look into whatever folder for the project files to add
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"
        volumes:
            - /app/node_modules
            - .:/app
        stdin_open: true
    tests:
        build: 
            context: . #look into whatever folder for the project files to add
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - .:/app
        command: ["npm", "run", "test"]